name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
